// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMsbBOvftG17sq7WOxPyzavmrqRxGC5U',
    appId: '1:262941798459:web:fb25ff060b476db378ac1e',
    messagingSenderId: '262941798459',
    projectId: 'connext-50ab2',
    authDomain: 'connext-50ab2.firebaseapp.com',
    storageBucket: 'connext-50ab2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXF-BT6oJ8MVmYFK3iLowHn9yKe7Zrt0',
    appId: '1:262941798459:android:08e56bee098a8a9278ac1e',
    messagingSenderId: '262941798459',
    projectId: 'connext-50ab2',
    storageBucket: 'connext-50ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcTWZ-uguOeZR4f61hdlRStcaOc5jYLM',
    appId: '1:262941798459:ios:0064c3833aadcf0d78ac1e',
    messagingSenderId: '262941798459',
    projectId: 'connext-50ab2',
    storageBucket: 'connext-50ab2.appspot.com',
    androidClientId:
        '262941798459-f30e1t7mdhvouag69ntul2ohuo5pgktb.apps.googleusercontent.com',
    iosClientId:
        '262941798459-b9o4e4uqnjis18f9iv29euvovh0qtcls.apps.googleusercontent.com',
    iosBundleId: 'com.ladeedahamed.connext',
  );
}
